plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation ("dev.boxadactle:Boxlib-fabric:${boxlib_version}") { transitive = false }

    implementation("com.terraformersmc:modmenu:${modmenu_version}") { transitive = false }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

import groovy.json.JsonSlurper
import groovy.json.JsonOutput

// someone pls make this work like its suppposed to
tasks.named('processResources') {
    doLast {
        def jsonFile = file("$buildDir/resources/main/${mod_id}.mixins.json")

        if (jsonFile.exists()) {
            def jsonSlurper = new JsonSlurper()
            def data = jsonSlurper.parse(jsonFile)

            data["refmap"] = "${mod_id}.refmap.json"

            jsonFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(data))
        } else {
            println "mixin config not found at ${jsonFile}"
        }
    }
}
