plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.10-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.97' apply false
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
    id "com.github.breadmoirai.github-release" version "2.5.2"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'java-library'

    repositories {
        // Fix issue with lwjgl-freetype not being found on macOS / ForgeGradle issue
        //
        // Could not resolve all files for configuration ':_compileJava_1'.
        // Could not find lwjgl-freetype-3.3.3-natives-macos-patch.jar (org.lwjgl:lwjgl-freetype:3.3.3).
        maven {
            url "https://libraries.minecraft.net"
            content {
                includeModule("org.lwjgl", "lwjgl-freetype")
            }
        }
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://repo.lucko.me/" }
        maven { url "https://jitpack.io" }
        maven { url = "https://maven.terraformersmc.com/releases/" }
        maven { url = "https://maven.boxadactle.dev/releases" }
        maven { url = "https://maven.boxadactle.dev/snapshots" }
    }
}


publishMods {
    changelog = new File(rootProject.rootDir, project.changelog_file).text
    type = STABLE

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        projectId = project.project_id_curseforge
        minecraftVersions.addAll(project.game_versions.split(","))
        changelogType = "markdown"
        javaVersions.add(JavaVersion.current())
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = project.project_id_modrinth
        minecraftVersions.addAll(project.game_versions.split(","))
    }

    curseforge("curseforgeFabric") {
        from cfOptions
        file project(":fabric")
        modLoaders.addAll("fabric", "quilt")
        requires {
            slug = "fabric-api"
        }
        displayName = "[Fabric ${project.minecraft_version}] v${project.version}"
    }

    curseforge("curseforgeForge") {
        from cfOptions
        file project(":forge")
        modLoaders.add("forge")
        displayName = "[Forge ${project.minecraft_version}] v${project.version}"
    }

    curseforge("curseforgeNeoforge") {
        from cfOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
        displayName = "[Neoforge ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthFabric") {
        from mrOptions
        file project(":fabric")
        modLoaders.addAll("fabric", "quilt")
        requires {
            slug = "fabric-api"
        }
        displayName = "[Fabric ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthForge") {
        from mrOptions
        file project(":forge")
        modLoaders.add("forge")
        displayName = "[Forge ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthNeoforge") {
        from mrOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
        displayName = "[Neoforge ${project.minecraft_version}] v${project.version}"
    }
}

githubRelease {
    owner = "Boxadactle"
    repo = "BoxLib"
    tagName = "$project.version"
    targetCommitish = "dev"
    releaseName = "BoxLib $project.version"
    generateReleaseNotes = true
    body = """BoxLib $project.version for Minecraft $project.minecraft_version

${new File(rootProject.rootDir, project.changelog_file).text}
"""
    authorization = "Token ${System.getenv("GITHUB_TOKEN")}"

    var files = []
    for (String platform : project.enabled_platforms.split(',')) {
        files += fileTree("$platform/build/libs") {
            include "*$project.version*"
        }
    }
    releaseAssets = files

//    dryRun = true
}
