# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=17.0.2
group=dev.boxadactle
java_version=21

# Common
minecraft_version=1.21.7
mod_name=Coordinates Display
mod_author=Boxadactle
mod_id=coordinatesdisplay
license=GNU GPLv3
credits=
description=A basic mod that displays your Coordinates on the In-game HUD.
enabled_platforms = fabric,forge,neoforge
minecraft_version_range=[1.21.6, 1.22)
minecraft_version_range_fabric = >=1.21.6
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.7-20250630.141722
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.5
parchment_version=2025.06.15

# Fabric
fabric_version=0.128.1+1.21.7
fabric_loader_version=0.16.14
modmenu_version=15.0.0-beta.3

# Forge
forge_version=57.0.2
forge_loader_version_range=[56,)

# NeoForge
neoforge_version=21.7.4-beta
neoforge_loader_version_range=[2,)

# BoxLib
boxlib_version=18.0.3-snapshot
boxlib_version_range = [18, 19)
boxlib_version_range_fabric=18.x

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# publishing
game_versions = 1.21.6,1.21.7
project_id_curseforge = 646464
project_id_modrinth = 3mW8PdUo
release_type = release
changelog_file = CHANGELOG.md
