# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=18.0.2
group=dev.boxadactle.coordinatesdisplay
java_version=21

# Common
minecraft_version=1.21.10
mod_name=CoordinatesDisplay
mod_author=Boxadactle
mod_id=coordinatesdisplay
license=GNU GPLv3
credits=
description=A basic mod that displays your Coordinates on the In-game HUD.
enabled_platforms=fabric,forge,neoforge
minecraft_version_range=[1.21.9, 1.22)
minecraft_version_range_fabric=>=1.21.9
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-20251010.172816
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.9
parchment_version=2025.10.05

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.135.0+1.21.10
fabric_loader_version=0.17.3
modmenu_version=16.0.0-rc.1

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=60.0.3
forge_loader_version_range=[60,)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.10.8-beta
neoforge_loader_version_range=[4,)

# BoxLib
boxlib_version=19.0.1-snapshot
boxlib_version_range = [19, 20)
boxlib_version_range_fabric=19.x

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# publishing
game_versions = 1.21.9,1.21.10
project_id_curseforge = 646464
project_id_modrinth = 3mW8PdUo
release_type = release
changelog_file = CHANGELOG.md