modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"

[[mods]]
modId = "coordinatesdisplay"
version = "${version}"
displayName = "Coordinates Display"
authors = "Boxadactle"
description = '''
A mod that displays your coordinates on the in-game HUD.
'''
logoFile = "icon.png"

[[dependencies.coordinatesdisplay]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coordinatesdisplay]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coordinatesdisplay]]
modId = "boxlib"
type = "required"
versionRange = "[16.0.0,17.0.0)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "coordinatesdisplay.mixins.json"