name: Compile
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up gradlew
        run: chmod +x ./gradlew

      - name: Compile java
        run: ./gradlew compileJava
