# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish
on:
  push:
    branches: [ "latest" ]

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up gradlew
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload fabric
      uses: actions/upload-artifact@v4
      with:
        name: fabric-build
        path: fabric/build/libs
        
    - name: Upload neoforge
      uses: actions/upload-artifact@v4
      with:
        name: neoforge-build
        path: neoforge/build/libs

    - name: Publish
      run: ./gradlew publishUnified
      env:
        CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

    - name: Create GitHub release
      run: ./gradlew githubRelease
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
